import { createSlice } from "@reduxjs/toolkit";

// Products data
const PRODUCTS = [
  // ---------------------- ELECTRONICS ----------------------
  {
    id: 1,
    name: "Wireless Headphones",
    price: 99,
    category: "electronics",
    image: "🎧",
    rating: 4.5,
    stock: 15,
  },
  {
    id: 2,
    name: "Smart Watch",
    price: 199,
    category: "electronics",
    image: "⌚",
    rating: 4.8,
    stock: 8,
  },
  {
    id: 3,
    name: "Laptop Stand",
    price: 49,
    category: "electronics",
    image: "💻",
    rating: 4.2,
    stock: 20,
  },
  {
    id: 4,
    name: "Mechanical Keyboard",
    price: 129,
    category: "electronics",
    image: "⌨️",
    rating: 4.7,
    stock: 12,
  },
  {
    id: 5,
    name: "Bluetooth Speaker",
    price: 79,
    category: "electronics",
    image: "🔊",
    rating: 4.6,
    stock: 18,
  },
  {
    id: 6,
    name: "Gaming Mouse",
    price: 59,
    category: "electronics",
    image: "🖱️",
    rating: 4.5,
    stock: 25,
  },
  {
    id: 7,
    name: "Portable Power Bank",
    price: 39,
    category: "electronics",
    image: "🔋",
    rating: 4.3,
    stock: 30,
  },
  {
    id: 8,
    name: "USB-C Charger",
    price: 29,
    category: "electronics",
    image: "⚡",
    rating: 4.2,
    stock: 28,
  },
  {
    id: 9,
    name: "Noise Cancelling Earbuds",
    price: 149,
    category: "electronics",
    image: "🎶",
    rating: 4.8,
    stock: 10,
  },
  {
    id: 10,
    name: "HD Webcam",
    price: 89,
    category: "electronics",
    image: "📷",
    rating: 4.4,
    stock: 16,
  },
  {
    id: 11,
    name: "Portable SSD",
    price: 129,
    category: "electronics",
    image: "💾",
    rating: 4.9,
    stock: 14,
  },
  {
    id: 12,
    name: "LED Monitor 24 inch",
    price: 199,
    category: "electronics",
    image: "🖥️",
    rating: 4.6,
    stock: 10,
  },

  // ---------------------- FASHION ----------------------
  {
    id: 13,
    name: "Denim Jacket",
    price: 79,
    category: "fashion",
    image: "🧥",
    rating: 4.4,
    stock: 10,
  },
  {
    id: 14,
    name: "Running Shoes",
    price: 89,
    category: "fashion",
    image: "👟",
    rating: 4.6,
    stock: 15,
  },
  {
    id: 15,
    name: "Backpack",
    price: 59,
    category: "fashion",
    image: "🎒",
    rating: 4.3,
    stock: 18,
  },
  {
    id: 16,
    name: "Sunglasses",
    price: 39,
    category: "fashion",
    image: "🕶️",
    rating: 4.1,
    stock: 25,
  },
  {
    id: 17,
    name: "Leather Belt",
    price: 29,
    category: "fashion",
    image: "🧷",
    rating: 4.2,
    stock: 28,
  },
  {
    id: 18,
    name: "Formal Shirt",
    price: 49,
    category: "fashion",
    image: "👔",
    rating: 4.5,
    stock: 22,
  },
  {
    id: 19,
    name: "Slim Fit Jeans",
    price: 60,
    category: "fashion",
    image: "👖",
    rating: 4.4,
    stock: 20,
  },
  {
    id: 20,
    name: "Hoodie",
    price: 55,
    category: "fashion",
    image: "🧥",
    rating: 4.6,
    stock: 18,
  },
  {
    id: 21,
    name: "Sports Cap",
    price: 25,
    category: "fashion",
    image: "🧢",
    rating: 4.3,
    stock: 30,
  },
  {
    id: 22,
    name: "Women’s Handbag",
    price: 70,
    category: "fashion",
    image: "👜",
    rating: 4.5,
    stock: 12,
  },
  {
    id: 23,
    name: "Casual T-Shirt",
    price: 20,
    category: "fashion",
    image: "👕",
    rating: 4.2,
    stock: 40,
  },
  {
    id: 24,
    name: "Winter Gloves",
    price: 19,
    category: "fashion",
    image: "🧤",
    rating: 4.4,
    stock: 35,
  },

  // ---------------------- BOOKS ----------------------
  {
    id: 25,
    name: "JavaScript Book",
    price: 45,
    category: "books",
    image: "📚",
    rating: 4.9,
    stock: 30,
  },
  {
    id: 26,
    name: "Design Patterns",
    price: 55,
    category: "books",
    image: "📖",
    rating: 4.7,
    stock: 20,
  },
  {
    id: 27,
    name: "React Handbook",
    price: 35,
    category: "books",
    image: "📘",
    rating: 4.8,
    stock: 25,
  },
  {
    id: 28,
    name: "Python Guide",
    price: 42,
    category: "books",
    image: "📕",
    rating: 4.6,
    stock: 22,
  },
  {
    id: 29,
    name: "Clean Code",
    price: 50,
    category: "books",
    image: "📗",
    rating: 4.9,
    stock: 18,
  },
  {
    id: 30,
    name: "Atomic Habits",
    price: 30,
    category: "books",
    image: "📙",
    rating: 4.9,
    stock: 25,
  },
  {
    id: 31,
    name: "Deep Work",
    price: 32,
    category: "books",
    image: "📘",
    rating: 4.7,
    stock: 21,
  },
  {
    id: 32,
    name: "You Don’t Know JS",
    price: 40,
    category: "books",
    image: "📚",
    rating: 4.8,
    stock: 27,
  },
  {
    id: 33,
    name: "Eloquent JavaScript",
    price: 28,
    category: "books",
    image: "📕",
    rating: 4.6,
    stock: 33,
  },
  {
    id: 34,
    name: "Node.js in Action",
    price: 48,
    category: "books",
    image: "📗",
    rating: 4.5,
    stock: 19,
  },
  {
    id: 35,
    name: "System Design Basics",
    price: 58,
    category: "books",
    image: "📘",
    rating: 4.8,
    stock: 15,
  },
  {
    id: 36,
    name: "CSS Mastery",
    price: 26,
    category: "books",
    image: "📙",
    rating: 4.3,
    stock: 28,
  },
];

const initialState = {
  items: PRODUCTS, // ⭐ Start with products already loaded!
  selectedCategory: "all",
  searchQuery: "",
};

const productsSlice = createSlice({
  name: "products",
  initialState,
  reducers: {
    setCategory: (state, action) => {
      state.selectedCategory = action.payload;
    },
    setSearchQuery: (state, action) => {
      state.searchQuery = action.payload;
    },
  },
});

export const { setCategory, setSearchQuery } = productsSlice.actions;
export default productsSlice.reducer;
